version: "3.9"
services:
  api-service:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    container_name: jobnav-api
    environment:
      JOBNAV_APP_ENV: dev
      JOBNAV_POSTGRES_DSN: postgresql://jobnav:jobnav@postgres:5432/jobnavigator
      JOBNAV_REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker-service:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.worker
    container_name: jobnav-worker
    environment:
      JOBNAV_APP_ENV: dev
      JOBNAV_POSTGRES_DSN: postgresql://jobnav:jobnav@postgres:5432/jobnavigator
      JOBNAV_REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg16
    container_name: jobnav-postgres
    environment:
      POSTGRES_DB: jobnavigator
      POSTGRES_USER: jobnav
      POSTGRES_PASSWORD: jobnav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: jobnav-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

